- name: Install tmux
  become: true
  become_user: root
  ansible.builtin.package:
    name: tmux
    state: present
- name: Install tpm (plugin manager)
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: ~/.tmux/plugins/tpm
    version: v3.1.0
