FROM mcr.microsoft.com/devcontainers/base:ubuntu22.04

RUN apt update \
    && apt upgrade -y && apt install -y curl

# create the use
# This is important if we want to use the ssh-agent

# RUN groupadd --gid ${UID} ${USER} \
#     && adduser --uid ${UID} --gid ${UID} ${USER}
ARG UID=1000
ENV SSH_AUTH_SOCK=/ssh-agent
RUN /usr/sbin/groupmod -g ${UID} vscode \
    && /usr/sbin/usermod -u ${UID} -g ${UID} vscode


USER vscode
RUN curl -sSf https://raw.githubusercontent.com/igorovic/wsl-init/main/wsl/setup2.sh | /sbin/sudo /bin/bash
#USER vscode

#CMD [ "/bin/zsh" ]