FROM mcr.microsoft.com/devcontainers/base:ubuntu22.04

RUN apt update \
    && apt upgrade -y 

RUN apt install -y gcc make jq git unzip tmux zsh ripgrep fzf wget pass
RUN wget -O /usr/bin/nvim-linux64.tar.gz https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz \
    && tar -xv -C /usr/bin/ -f /usr/bin/nvim-linux64.tar.gz \
    && ln -fs /usr/bin/nvim-linux64/bin/nvim /usr/bin/nvim \
    && ln -fs /usr/bin/nvim-linux64/bin/nvim /usr/local/bin/nvim \
    && rm /usr/bin/nvim-linux64.tar.gz \
    && rm -rf /root/.oh-my-zsh

# change user's UID to match the host
# This is important if we want to use the ssh-agent
ARG UID=1000
ENV SSH_AUTH_SOCK=/ssh-agent
RUN /usr/sbin/groupmod -g ${UID} vscode \
    && /usr/sbin/usermod -u ${UID} -g ${UID} vscode
RUN chown -R ${UID}:${UID} /home/vscode
RUN chsh -s /bin/zsh vscode

USER vscode

WORKDIR /home/vscode
CMD [ "/bin/zsh" ]