---
- name: Bitwarden secret manager
  hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Find latest release
      ansible.builtin.shell:
        # we use github cli to call the api authenticated - to avoid rate limiting
        cmd: 'gh api --method GET /repos/bitwarden/sdk/releases/latest --header "Accept: application/vnd.github+json" --header "X-GitHub-Api-Version: 2022-11-28" | jq ".assets[] | select(.name | test(\"$(uname -m).*linux\"))"'
      register: out
    - name: Show
      ansible.builtin.debug:
        var: out.stdout_lines|join|from_json|json_query('browser_download_url')
    - name: Download bws cli
      get_url:
        url: "{{out.stdout_lines|join|from_json|json_query('browser_download_url')}}"
        dest: /tmp/bws.zip
    - name: Install bws cli
      ansible.builtin.shell:
        cmd: 'cd /tmp/ && unzip -o bws.zip && mv ./bws /usr/bin/bws'