---
- name: Create user
  hosts: localhost
  connection: localhost
  gather_facts: false
  vars_prompt:
    - name: username
      prompt: "Username"
      private: false
    - name: password
      private: true
      prompt: "Password"
      encrypt: sha512_crypt
      confirm: true
      salt_size: 8
      unsafe: false
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password }}"
        shell: /usr/bin/bash
        create_home: true
        groups: adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev
    - name: Export username
      ansible.builtin.set_fact:
        new_user: "test"
